import { config } from "../../config";
import { Grid2D } from "../Grid2D";
import { WorldState } from "../WorldState";
import { generateMountain } from "../terrain/generateMountain";
import { totalWaterVolume } from "../hydrology/fluxStep";
import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

export type ProbeRecord = Record<string, number | string>;

export type ProbeResult = {
  scenario: string;
  records: ProbeRecord[];
};

function ensureEvidenceDir(): string {
  const dir = join(process.cwd(), "docs/evidence");
  mkdirSync(dir, { recursive: true });
  return dir;
}

function writeEvidence(scenario: string, rows: ProbeRecord[]): void {
  const dir = ensureEvidenceDir();
  const keys = [...new Set(rows.flatMap((r) => Object.keys(r)))];
  const lines = [
    `# Probe — ${scenario}`,
    "",
    `Generated by \`npm run probe -- ${scenario}\`. Tier-M evidence (VERIFICATION_POLICY §8).`,
    "",
    `| ${keys.join(" | ")} |`,
    `| ${keys.map(() => "---").join(" | ")} |`,
    ...rows.map((r) => `| ${keys.map((k) => r[k] ?? "").join(" | ")} |`),
    "",
  ];
  writeFileSync(join(dir, `${scenario}.md`), lines.join("\n"));
}

export function probePairedStorm(): ProbeResult {
  const terrain = generateMountain(32, 32, 8, 11);
  const bare = new WorldState(terrain.clone());
  const veg = new WorldState(terrain.clone());
  bare.vegCover.fill(0);
  veg.vegCover.fill(1);
  bare.runVegetationStep(1);
  veg.runVegetationStep(1);
  bare.runSoilWaterStep(1);
  veg.runSoilWaterStep(1);

  const run = (world: WorldState): ProbeRecord => {
    let peak = 0;
    let timeToPeak = 0;
    for (let i = 0; i < 120; i++) {
      world.addRain(config.rainDepthPerEvent);
      world.runSurfaceWaterStep(config.eventFluxDt);
      if (i % 5 === 4) world.runSoilWaterStep(1);
      const vol = totalWaterVolume(world.water.data);
      if (vol > peak) {
        peak = vol;
        timeToPeak = i;
      }
    }
    world.runSoilWaterStep(1);
    return {
      cover: world.vegCover.get(0, 0),
      peakSurface: peak,
      timeToPeak,
      finalSurface: totalWaterVolume(world.water.data),
      infiltrated: world.infiltrationLedger,
      et: world.etLedger,
      massResidual: world.waterBalanceResidual(),
    };
  };

  const records = [
    { label: "bare", ...run(bare) },
    { label: "vegetated", ...run(veg) },
  ];
  writeEvidence("paired-storm", records);
  return { scenario: "paired-storm", records };
}

export function probeBermReroute(): ProbeResult {
  // Ramp so a mid-slope berm clearly redirects accumulation (A-005 / Tier-M).
  const w = 24;
  const h = 24;
  const terrain = new Grid2D(w, h);
  for (let z = 0; z < h; z++) {
    for (let x = 0; x < w; x++) {
      terrain.set(x, z, x * 0.4);
    }
  }
  const world = new WorldState(terrain);
  world.ensureStructureFresh();
  const before = world.flowAccumulation!.slice();
  world.raiseBerm(12, 12, 3);
  world.ensureStructureFresh();
  const after = world.flowAccumulation!;
  let changed = 0;
  let maxDelta = 0;
  for (let i = 0; i < before.length; i++) {
    const d = Math.abs((after[i] ?? 0) - (before[i] ?? 0));
    if (d > 0) changed++;
    maxDelta = Math.max(maxDelta, d);
  }
  const records = [
    {
      cellsChanged: changed,
      maxAccumulationDelta: maxDelta,
      bermCellAccBefore: before[12 * w + 12] ?? 0,
      bermCellAccAfter: after[12 * w + 12] ?? 0,
    },
  ];
  if (changed === 0) {
    throw new Error("berm-reroute: expected flow accumulation to change");
  }
  writeEvidence("berm-reroute", records);
  return { scenario: "berm-reroute", records };
}

export function probeBasinFill(): ProbeResult {
  const w = 16;
  const h = 16;
  const terrain = new Grid2D(w, h, 4);
  for (let z = 4; z < 12; z++) {
    for (let x = 4; x < 12; x++) {
      terrain.set(x, z, 1);
    }
  }
  terrain.set(8, 8, 0);
  const world = new WorldState(terrain);
  world.ensureStructureFresh();
  const pit = 8 * w + 8;
  const depth = world.depressionDepth.data[pit]!;
  const filled = world.filledElevation![pit]!;

  world.water.fill(0);
  world.water.set(8, 8, depth);
  const initial = totalWaterVolume(world.water.data);
  for (let i = 0; i < 40; i++) world.runSurfaceWaterStep(config.eventFluxDt);
  const residual = Math.abs(totalWaterVolume(world.water.data) - initial);

  const records = [
    {
      pitRawElev: 0,
      spillFilledElev: filled,
      depressionDepth: depth,
      volumeResidual: residual,
    },
  ];
  writeEvidence("basin-fill", records);
  return { scenario: "basin-fill", records };
}

const SCENARIOS: Record<string, () => ProbeResult> = {
  "paired-storm": probePairedStorm,
  "berm-reroute": probeBermReroute,
  "basin-fill": probeBasinFill,
};

export function runProbe(name: string): ProbeResult {
  const fn = SCENARIOS[name];
  if (!fn) {
    throw new Error(
      `Unknown probe '${name}'. Known: ${Object.keys(SCENARIOS).join(", ")}`,
    );
  }
  return fn();
}

export function listProbes(): string[] {
  return Object.keys(SCENARIOS);
}
