#!/usr/bin/env npx tsx
/**
 * Headless probes (VERIFICATION_POLICY §8, T-006, BUILD_GUIDE §4.1).
 *
 * Usage:
 *   npm run probe -- --list
 *   npm run probe -- <scenario>              # run + rewrite evidence md vs baseline
 *   npm run probe -- --all --check           # every scenario; write nothing; non-zero on drift
 *   npm run probe -- <scenario> --write-baseline   # intentional baseline refresh (state why in commit)
 */
import {
  compareToBaseline,
  formatCheckFailure,
  writeBaselineFile,
  writeEvidenceMarkdown,
  type MetricTolerance,
} from "../src/sim/probes/baseline.ts";
import { listProbes, runProbe } from "../src/sim/probes/scenarios.ts";

/** Tolerances chosen with the scenario (not fitted after a noisy run). */
const BASELINE_TOLERANCES: Record<string, Record<string, MetricTolerance>> = {
  "paired-storm": {
    // f32 cover / roughness from veg step
    "bare.cover": { abs: 1e-6 },
    "bare.downslope": { abs: 1e-5 },
    "bare.roughness": { abs: 1e-6 },
    "bare.infiltrated": { abs: 1e-4 },
    "vegetated.cover": { abs: 1e-6 },
    "vegetated.downslope": { abs: 1e-5 },
    "vegetated.roughness": { abs: 1e-6 },
    "vegetated.infiltrated": { abs: 1e-4 },
  },
  "berm-reroute": {
    // Exact integer accumulation topology
    "row0.cellsChanged": { abs: 0 },
    "row0.maxAccumulationDelta": { abs: 0 },
    "row0.bermCellAccBefore": { abs: 0 },
    "row0.bermCellAccAfter": { abs: 0 },
  },
  "basin-fill": {
    "row0.pitRawElev": { abs: 0 },
    "row0.spillFilledElev": { abs: 0 },
    "row0.depressionDepth": { abs: 0 },
    // Mass residual is ~1e-8 today; abs 1e-6 catches real leaks, not fp dust
    "row0.volumeResidual": { abs: 1e-6 },
  },
  "deep-time": {
    // Interval means — f32 geomorphology / veg over compressed decades
    "y0.meanElev": { abs: 1e-5 },
    "y0.meanSoilDepth": { abs: 1e-5 },
    "y0.meanCover": { abs: 1e-5 },
    "y0.massResidual": { abs: 1e-3 },
    "y0.stepMsMean": { abs: 1e9 },
    "y20.meanElev": { abs: 1e-5 },
    "y20.meanSoilDepth": { abs: 1e-5 },
    "y20.meanCover": { abs: 1e-5 },
    "y20.massResidual": { abs: 1e-3 },
    "y20.stepMsMean": { abs: 1e9 },
    "y40.meanElev": { abs: 1e-5 },
    "y40.meanSoilDepth": { abs: 1e-5 },
    "y40.meanCover": { abs: 1e-5 },
    "y40.massResidual": { abs: 1e-3 },
    "y40.stepMsMean": { abs: 1e9 },
    "y60.meanElev": { abs: 1e-5 },
    "y60.meanSoilDepth": { abs: 1e-5 },
    "y60.meanCover": { abs: 1e-5 },
    "y60.massResidual": { abs: 1e-3 },
    "y60.stepMsMean": { abs: 1e9 },
    "y80.meanElev": { abs: 1e-5 },
    "y80.meanSoilDepth": { abs: 1e-5 },
    "y80.meanCover": { abs: 1e-5 },
    "y80.massResidual": { abs: 1e-3 },
    "y80.stepMsMean": { abs: 1e9 },
    "y100.meanElev": { abs: 1e-5 },
    "y100.meanSoilDepth": { abs: 1e-5 },
    "y100.meanCover": { abs: 1e-5 },
    "y100.massResidual": { abs: 1e-3 },
    "y100.stepMsMean": { abs: 1e9 },
    // Late motion must stay non-zero (f32-stall tripwire); values are scenario-locked
    "lateDelta.soilDepthDelta": { abs: 1e-6 },
    "lateDelta.elevDelta": { abs: 1e-6 },
    "lateDelta.coverDelta": { abs: 1e-6 },
    "lateDelta.stillMoving": { abs: 0 },
    // P-005
    "p005.hashMatch": { abs: 0 },
    "p005.simYears": { abs: 0 },
    "p005.legacyThinGainedMore": { abs: 0 },
    "p005.hashFirstN": { abs: 0 },
    "p005.hashSecondN": { abs: 0 },
  },
  "baseflow-persist": {
    "withGw.channelWet": { abs: 1e-5 },
    "withGw.gwSum": { abs: 1e-3 },
    "withGw.massResidual": { abs: 1e-3 },
    "withoutGw.channelWet": { abs: 0 },
    "withoutGw.gwSum": { abs: 0 },
    "withoutGw.massResidual": { abs: 1e-3 },
    "delta.channelWetDelta": { abs: 1e-5 },
    "delta.ratio": { abs: 1 },
  },
  "regime-divergence": {
    "light.hashN": { abs: 0 },
    "light.precip": { abs: 1e-6 },
    "light.soilSum": { abs: 1e-4 },
    "light.meanCover": { abs: 1e-5 },
    "light.replayMatch": { abs: 0 },
    "heavy.hashN": { abs: 0 },
    "heavy.precip": { abs: 1e-6 },
    "heavy.soilSum": { abs: 1e-4 },
    "heavy.meanCover": { abs: 1e-5 },
    "delta.precipDelta": { abs: 1e-6 },
    "delta.soilDelta": { abs: 1e-4 },
    "delta.hashDiverged": { abs: 0 },
  },
  "branch-compare": {
    "same.hashMatch": { abs: 0 },
    "same.hashN": { abs: 0 },
    "same.precip": { abs: 1e-5 },
    "heavy.hashN": { abs: 0 },
    "heavy.precip": { abs: 1e-5 },
    "heavy.meanSoil": { abs: 1e-5 },
    "dry.hashN": { abs: 0 },
    "dry.precip": { abs: 1e-5 },
    "dry.meanSoil": { abs: 1e-5 },
    "delta.hashDiverged": { abs: 0 },
    "delta.precipDelta": { abs: 1e-5 },
    "delta.soilDelta": { abs: 1e-5 },
    "delta.encoding": { abs: 1e-4 },
    "delta.encodingCleared": { abs: 0 },
    "delta.isolated": { abs: 0 },
  },
  "limiting-shift": {
    "wet.limiting": { abs: 0 },
    "wet.hsi": { abs: 1e-6 },
    "wet.depthLimited": { abs: 0 },
    "dry.limiting": { abs: 0 },
    "dry.hsi": { abs: 1e-6 },
    "dry.moistureLimited": { abs: 0 },
    "shift.identityChanged": { abs: 0 },
    "shift.hsiDrop": { abs: 1e-6 },
  },
  "burn-recover": {
    "fire.burnedCells": { abs: 0 },
    "fire.fuelBefore": { abs: 1e-4 },
    "fire.fuelAfter": { abs: 1e-4 },
    "fire.consumed": { abs: 1e-3 },
    "fire.accountingError": { abs: 1e-3 },
    "fire.determinismMatch": { abs: 0 },
    "fire.hashN": { abs: 0 },
    "wetSector.coverAfterBurn": { abs: 1e-6 },
    "wetSector.coverRecovered": { abs: 1e-5 },
    "drySector.coverAfterBurn": { abs: 1e-6 },
    "drySector.coverRecovered": { abs: 1e-5 },
    "delta.recoveryGap": { abs: 1e-4 },
    "delta.wetVsDry": { abs: 0.1 },
  },
  "succession-diverge": {
    "south.meanInsolation": { abs: 1e-6 },
    "south.meanUnderstoryLight": { abs: 1e-6 },
    "south.meanCover": { abs: 1e-6 },
    "south.replayMatch": { abs: 0 },
    "north.meanInsolation": { abs: 1e-6 },
    "north.meanUnderstoryLight": { abs: 1e-6 },
    "north.meanCover": { abs: 1e-6 },
    "delta.insolationGap": { abs: 1e-6 },
    "delta.coverGap": { abs: 1e-6 },
  },
  "drydown-feedback": {
    "southBare.moistureAfterDry": { abs: 1e-5 },
    "southBare.meanPet": { abs: 1e-6 },
    "southBare.etTotal": { abs: 1e-4 },
    "southBare.transpiration": { abs: 1e-4 },
    "southBare.soilEvaporation": { abs: 1e-4 },
    "southBare.massResidual": { abs: 1e-3 },
    "southBare.replayMatch": { abs: 0 },
    "southVeg.moistureAfterDry": { abs: 1e-5 },
    "southVeg.transpiration": { abs: 1e-4 },
    "southVeg.soilEvaporation": { abs: 1e-4 },
    "northBare.moistureAfterDry": { abs: 1e-5 },
    "northBare.meanPet": { abs: 1e-6 },
    "delta.petGap": { abs: 1e-6 },
    "delta.moistureGap": { abs: 1e-5 },
    "delta.transpirationGap": { abs: 1e-4 },
    "delta.relResidual": { abs: 1e-5 },
  },
  "disturbance-recovery": {
    "pulse.baseline": { abs: 1e-5 },
    "pulse.peak": { abs: 1e-5 },
    "pulse.halfTarget": { abs: 1e-5 },
    "pulse.finalMoisture": { abs: 1e-5 },
    "pulse.recoveredDay": { abs: 0 },
    "pulse.earlyDrop": { abs: 1e-5 },
    "pulse.lateDrop": { abs: 1e-5 },
    "pulse.risingDays": { abs: 0 },
    "pulse.relResidual": { abs: 1e-5 },
    "pulse.bounded": { abs: 0 },
  },
  "arrival-earned": {
    "suitable.hsi": { abs: 1e-6 },
    "suitable.seedBank": { abs: 1e-5 },
    "suitable.establishment": { abs: 1e-6 },
    "suitable.biomass": { abs: 1e-5 },
    "unsuitable.hsi": { abs: 0 },
    "unsuitable.seedBank": { abs: 1e-5 },
    "unsuitable.establishment": { abs: 1e-6 },
    "unsuitable.biomass": { abs: 0 },
    "delta.biomassDelta": { abs: 1e-5 },
    "delta.hashMatch": { abs: 0 },
    "delta.bounded": { abs: 0 },
    "delta.earned": { abs: 0 },
  },
  "living-hollow": {
    "colonized.cover": { abs: 0 },
    "colonized.biomass": { abs: 1e-5 },
    "colonized.downslope": { abs: 1e-5 },
    "colonized.roughness": { abs: 1e-6 },
    "colonized.infiltrated": { abs: 1e-4 },
    "bare.cover": { abs: 0 },
    "bare.biomass": { abs: 0 },
    "bare.downslope": { abs: 1e-5 },
    "bare.roughness": { abs: 1e-6 },
    "bare.infiltrated": { abs: 1e-4 },
    "delta.biomassDelta": { abs: 1e-5 },
    "delta.downslopeDelta": { abs: 1e-5 },
    "delta.infilDelta": { abs: 1e-4 },
    "delta.hashMatch": { abs: 0 },
    "delta.bounded": { abs: 0 },
    "delta.coverHeld": { abs: 0 },
    "delta.earned": { abs: 0 },
  },
  "scenario-window": {
    "meet.satisfied": { abs: 0 },
    "meet.achieved": { abs: 0 },
    "meet.achievedAt": { abs: 0 },
    "meet.rollingMet": { abs: 0 },
    "meet.samples": { abs: 0 },
    "meet.worldHashMatch": { abs: 0 },
    "fail.satisfied": { abs: 0 },
    "fail.achieved": { abs: 0 },
    "fail.achievedAt": { abs: 0 },
    "fail.rollingMet": { abs: 0 },
    "fail.samples": { abs: 0 },
    "fail.worldHashMatch": { abs: 0 },
    "delta.hashMatch": { abs: 0 },
    "delta.pairedDiverge": { abs: 0 },
    "delta.writeIsolated": { abs: 0 },
    "delta.outcomeHashNum": { abs: 0 },
  },
  "island-drainage": {
    "mid.oceanExchange": { abs: 1e-2 },
    "mid.precip": { abs: 1e-2 },
    "mid.massResidual": { abs: 1e-3 },
    "mid.relResidual": { abs: 1e-6 },
    "mid.oceanCells": { abs: 0 },
    "mid.shorelineCells": { abs: 0 },
    "mid.habitatZones": { abs: 0 },
    "mid.shoreFrac": { abs: 1e-4 },
    "mid.stepMsMean": { abs: 1e9 },
    "mid.replayMatch": { abs: 0 },
    "mid.hashN": { abs: 0 },
    "high.oceanCells": { abs: 0 },
    "high.shorelineCells": { abs: 0 },
    "high.oceanExchange": { abs: 1e-2 },
    "delta.oceanCellDelta": { abs: 0 },
    "delta.conserved": { abs: 0 },
    "delta.habitatMosaic": { abs: 0 },
    "delta.stepMs64": { abs: 1e9 },
  },
  "orographic-wind": {
    "west.precip": { abs: 1e-2 },
    "west.relResidual": { abs: 1e-6 },
    "west.sideEncoding": { abs: 1e-4 },
    "west.replayMatch": { abs: 0 },
    "west.hashN": { abs: 0 },
    "east.precip": { abs: 1e-2 },
    "east.sideEncoding": { abs: 1e-4 },
    "east.hashN": { abs: 0 },
    "delta.hashDiverged": { abs: 0 },
    "delta.precipRatio": { abs: 1e-4 },
    "delta.conserved": { abs: 0 },
    "delta.encodingFloor": { abs: 0 },
    "delta.calmPrecip": { abs: 1e-2 },
  },
  "tidal-envelope": {
    "off.intertidalCells": { abs: 0 },
    "off.oceanCells": { abs: 0 },
    "neap.intertidalCells": { abs: 0 },
    "neap.foreshoreFrac": { abs: 1e-4 },
    "neap.mhw": { abs: 1e-6 },
    "neap.mlw": { abs: 1e-6 },
    "mean.intertidalCells": { abs: 0 },
    "mean.foreshoreFrac": { abs: 1e-4 },
    "mean.replayMatch": { abs: 0 },
    "mean.hashN": { abs: 0 },
    "mean.encodingDelta": { abs: 1e-4 },
    "spring.intertidalCells": { abs: 0 },
    "spring.foreshoreFrac": { abs: 1e-4 },
    "spring.mhw": { abs: 1e-6 },
    "spring.mlw": { abs: 1e-6 },
    "delta.neapToMean": { abs: 0 },
    "delta.meanToSpring": { abs: 0 },
    "delta.foreshoreGrew": { abs: 0 },
    "delta.oceanUnchanged": { abs: 0 },
    "delta.encodingFloor": { abs: 0 },
  },
  "shore-exposure": {
    "west.westLoss": { abs: 1e-4 },
    "west.eastLoss": { abs: 1e-4 },
    "west.meanExpWest": { abs: 1e-4 },
    "west.meanExpEast": { abs: 1e-4 },
    "west.shoreErosion": { abs: 1e-3 },
    "west.bedrockOk": { abs: 0 },
    "west.replayMatch": { abs: 0 },
    "west.hashN": { abs: 0 },
    "east.westLoss": { abs: 1e-4 },
    "east.eastLoss": { abs: 1e-4 },
    "east.meanExpWest": { abs: 1e-4 },
    "east.meanExpEast": { abs: 1e-4 },
    "east.shoreErosion": { abs: 1e-3 },
    "east.hashN": { abs: 0 },
    "delta.hashDiverged": { abs: 0 },
    "delta.westWindwardBias": { abs: 1e-4 },
    "delta.eastWindwardBias": { abs: 1e-4 },
    "delta.bedrockClosed": { abs: 0 },
    "delta.noSwe": { abs: 0 },
  },
  "longshore-drift": {
    "west.westDelta": { abs: 1e-4 },
    "west.eastDelta": { abs: 1e-4 },
    "west.shoreErosion": { abs: 1e-3 },
    "west.bedrockOk": { abs: 0 },
    "west.soilDelta": { abs: 1e-3 },
    "west.replayMatch": { abs: 0 },
    "west.hashN": { abs: 0 },
    "east.westDelta": { abs: 1e-4 },
    "east.eastDelta": { abs: 1e-4 },
    "east.shoreErosion": { abs: 1e-3 },
    "east.hashN": { abs: 0 },
    "calm.westDelta": { abs: 1e-4 },
    "calm.eastDelta": { abs: 1e-4 },
    "calm.shoreErosion": { abs: 1e-3 },
    "delta.hashDiverged": { abs: 0 },
    "delta.westLeeGain": { abs: 1e-4 },
    "delta.eastLeeGain": { abs: 1e-4 },
    "delta.westWindwardLoss": { abs: 1e-4 },
    "delta.bedrockClosed": { abs: 0 },
    "delta.noSwe": { abs: 0 },
  },
  "salinity-arrival": {
    "freshened.hsi": { abs: 1e-6 },
    "freshened.biomass": { abs: 1e-6 },
    "freshened.limiting": { abs: 0 },
    "freshened.salinity": { abs: 0 },
    "salty.hsi": { abs: 1e-6 },
    "salty.biomass": { abs: 1e-6 },
    "salty.limiting": { abs: 0 },
    "salty.salinity": { abs: 0 },
    "salty.saltLimited": { abs: 0 },
    "delta.biomassDelta": { abs: 1e-6 },
    "delta.hsiDelta": { abs: 1e-6 },
    "delta.replayMatch": { abs: 0 },
    "delta.residualMatch": { abs: 0 },
    "delta.hashN": { abs: 0 },
  },
  "substrate-contrast": {
    "sand.infiltrated": { abs: 1e-4 },
    "sand.erode": { abs: 1e-5 },
    "sand.porosity": { abs: 0 },
    "sand.infilRate": { abs: 0 },
    "sand.erosionK": { abs: 0 },
    "clay.infiltrated": { abs: 1e-4 },
    "clay.erode": { abs: 1e-5 },
    "clay.porosity": { abs: 0 },
    "clay.infilRate": { abs: 0 },
    "clay.erosionK": { abs: 0 },
    "delta.infilDelta": { abs: 1e-4 },
    "delta.erodeDelta": { abs: 1e-5 },
    "delta.replayMatch": { abs: 0 },
    "delta.tableDriven": { abs: 0 },
    "delta.hashN": { abs: 0 },
  },
  "substrate-deposit": {
    "sand.infiltrated": { abs: 1e-4 },
    "sand.erode": { abs: 1e-5 },
    "sand.porosity": { abs: 0 },
    "sand.infilRate": { abs: 0 },
    "sand.erosionK": { abs: 0 },
    "sand.stamped": { abs: 0 },
    "rock.infiltrated": { abs: 1e-4 },
    "rock.erode": { abs: 1e-5 },
    "rock.porosity": { abs: 0 },
    "rock.infilRate": { abs: 0 },
    "rock.erosionK": { abs: 0 },
    "rock.stamped": { abs: 0 },
    "delta.infilDelta": { abs: 1e-4 },
    "delta.erodeDelta": { abs: 1e-5 },
    "delta.replayMatch": { abs: 0 },
    "delta.tableDriven": { abs: 0 },
    "delta.stamped": { abs: 0 },
    "delta.hashN": { abs: 0 },
  },
  "hillslope-deposit": {
    "run.pitGain": { abs: 1e-5 },
    "run.channelLoss": { abs: 1e-5 },
    "run.sumDelta": { abs: 1e-5 },
    "run.bedrockOk": { abs: 0 },
    "run.replayMatch": { abs: 0 },
    "run.massOk": { abs: 0 },
    "run.hashN": { abs: 0 },
  },
  "island-arrival": {
    "small.landCells": { abs: 0 },
    "small.sElig": { abs: 1e-6 },
    "small.seed": { abs: 1e-6 },
    "small.biomass": { abs: 1e-6 },
    "small.hsi": { abs: 1e-6 },
    "small.notPerimeter": { abs: 0 },
    "small.oceanSeedZero": { abs: 0 },
    "large.landCells": { abs: 0 },
    "large.sElig": { abs: 1e-6 },
    "large.seed": { abs: 1e-6 },
    "large.biomass": { abs: 1e-6 },
    "large.hsi": { abs: 1e-6 },
    "isolation.nearBiomass": { abs: 1e-6 },
    "isolation.farBiomass": { abs: 1e-6 },
    "isolation.nearSElig": { abs: 1e-6 },
    "isolation.farSElig": { abs: 1e-6 },
    "isolation.isolationDelta": { abs: 1e-6 },
    "delta.landDelta": { abs: 0 },
    "delta.sEligDelta": { abs: 1e-6 },
    "delta.biomassDelta": { abs: 1e-6 },
    "delta.replayMatch": { abs: 0 },
    "delta.hashN": { abs: 0 },
  },
  "cloud-delivery": {
    "warm.precip": { abs: 1e-2 },
    "warm.peakCloud": { abs: 1e-4 },
    "warm.phase": { abs: 0 },
    "warm.relResidual": { abs: 1e-6 },
    "warm.replayMatch": { abs: 0 },
    "warm.hashN": { abs: 0 },
    "cold.precip": { abs: 1e-2 },
    "cold.peakCloud": { abs: 1e-4 },
    "cold.phase": { abs: 0 },
    "cold.hashN": { abs: 0 },
    "delta.phaseDiverged": { abs: 0 },
    "delta.conserved": { abs: 0 },
    "delta.precipRatio": { abs: 1e-3 },
  },
  "heat-arrival": {
    "warm.hsi": { abs: 1e-6 },
    "warm.biomass": { abs: 1e-6 },
    "warm.limiting": { abs: 0 },
    "warm.airTempC": { abs: 0 },
    "mild.hsi": { abs: 1e-6 },
    "mild.biomass": { abs: 1e-6 },
    "mild.limiting": { abs: 0 },
    "mild.airTempC": { abs: 0 },
    "cold.hsi": { abs: 1e-6 },
    "cold.biomass": { abs: 1e-6 },
    "cold.limiting": { abs: 0 },
    "cold.airTempC": { abs: 0 },
    "cold.tempLimited": { abs: 0 },
    "delta.biomassDelta": { abs: 1e-6 },
    "delta.hsiDelta": { abs: 1e-6 },
    "delta.mildBetween": { abs: 0 },
    "delta.replayMatch": { abs: 0 },
    "delta.hashN": { abs: 0 },
  },
  "strand-arrival": {
    "shore.strandBiomass": { abs: 1e-6 },
    "shore.herbBiomass": { abs: 1e-6 },
    "shore.salinity": { abs: 0 },
    "shore.exposure": { abs: 0 },
    "shore.herbLimiting": { abs: 0 },
    "inland.strandBiomass": { abs: 1e-6 },
    "inland.herbBiomass": { abs: 1e-6 },
    "inland.salinity": { abs: 0 },
    "inland.exposure": { abs: 0 },
    "inland.herbLimiting": { abs: 0 },
    "delta.shoreGuildDelta": { abs: 1e-6 },
    "delta.inlandGuildDelta": { abs: 1e-6 },
    "delta.seedMatch": { abs: 0 },
    "delta.guildSeedMatch": { abs: 0 },
    "delta.replayMatch": { abs: 0 },
    "delta.hashN": { abs: 0 },
  },
  "binder-arrival": {
    "crest.binderBiomass": { abs: 1e-6 },
    "crest.herbBiomass": { abs: 1e-6 },
    "crest.moisture": { abs: 1e-6 },
    "crest.exposure": { abs: 0 },
    "crest.material": { abs: 0 },
    "hollow.binderBiomass": { abs: 1e-6 },
    "hollow.herbBiomass": { abs: 1e-6 },
    "hollow.moisture": { abs: 1e-6 },
    "hollow.exposure": { abs: 0 },
    "hollow.material": { abs: 0 },
    "delta.crestGuildDelta": { abs: 1e-6 },
    "delta.hollowGuildDelta": { abs: 1e-6 },
    "delta.seedMatch": { abs: 0 },
    "delta.guildSeedMatch": { abs: 0 },
    "delta.replayMatch": { abs: 0 },
    "delta.hashN": { abs: 0 },
  },
  "spray-arrival": {
    "lee.hsi": { abs: 1e-6 },
    "lee.herbBiomass": { abs: 1e-6 },
    "lee.strandBiomass": { abs: 1e-6 },
    "lee.exposure": { abs: 0 },
    "lee.limiting": { abs: 0 },
    "lee.salinity": { abs: 0 },
    "windward.hsi": { abs: 1e-6 },
    "windward.herbBiomass": { abs: 1e-6 },
    "windward.strandBiomass": { abs: 1e-6 },
    "windward.exposure": { abs: 0 },
    "windward.limiting": { abs: 0 },
    "windward.sprayLimited": { abs: 0 },
    "windward.salinity": { abs: 0 },
    "delta.herbDelta": { abs: 1e-6 },
    "delta.hsiDelta": { abs: 1e-6 },
    "delta.saltMatch": { abs: 0 },
    "delta.replayMatch": { abs: 0 },
    "delta.hashN": { abs: 0 },
  },
  "inundation-arrival": {
    "dry.hsi": { abs: 1e-6 },
    "dry.herbBiomass": { abs: 1e-6 },
    "dry.amplitude": { abs: 0 },
    "dry.intertidal": { abs: 0 },
    "dry.limiting": { abs: 0 },
    "dry.salinity": { abs: 0 },
    "dry.exposure": { abs: 0 },
    "wet.hsi": { abs: 1e-6 },
    "wet.herbBiomass": { abs: 1e-6 },
    "wet.amplitude": { abs: 0 },
    "wet.intertidal": { abs: 0 },
    "wet.limiting": { abs: 0 },
    "wet.inundationLimited": { abs: 0 },
    "wet.salinity": { abs: 0 },
    "wet.exposure": { abs: 0 },
    "delta.herbDelta": { abs: 1e-6 },
    "delta.hsiDelta": { abs: 1e-6 },
    "delta.saltMatch": { abs: 0 },
    "delta.sprayMatch": { abs: 0 },
    "delta.replayMatch": { abs: 0 },
    "delta.hashN": { abs: 0 },
  },
  "light-arrival": {
    "south.hsi": { abs: 1e-6 },
    "south.herbBiomass": { abs: 1e-6 },
    "south.insolation": { abs: 1e-6 },
    "south.limiting": { abs: 0 },
    "south.moisture": { abs: 1e-6 },
    "north.hsi": { abs: 1e-6 },
    "north.herbBiomass": { abs: 1e-6 },
    "north.insolation": { abs: 1e-6 },
    "north.limiting": { abs: 0 },
    "north.lightLimited": { abs: 0 },
    "north.moisture": { abs: 1e-6 },
    "delta.herbDelta": { abs: 1e-6 },
    "delta.hsiDelta": { abs: 1e-6 },
    "delta.insolationGap": { abs: 1e-6 },
    "delta.moistureMatch": { abs: 0 },
    "delta.replayMatch": { abs: 0 },
    "delta.hashN": { abs: 0 },
  },
};

const args = process.argv.slice(2);
const list = args.includes("--list");
const all = args.includes("--all");
const check = args.includes("--check");
const writeBaseline = args.includes("--write-baseline");
const positional = args.filter((a) => !a.startsWith("--"));

function usage(): never {
  console.log(`Usage:
  npm run probe -- --list
  npm run probe -- <scenario>
  npm run probe -- --all --check
  npm run probe -- <scenario> --write-baseline`);
  process.exit(1);
}

if (list || args.length === 0) {
  console.log("Probes:", listProbes().join(", "));
  if (!list) usage();
  process.exit(0);
}

if (all && check) {
  let failed = false;
  for (const name of listProbes()) {
    const result = runProbe(name);
    const report = compareToBaseline(result);
    if (!report.ok) {
      failed = true;
      console.error(formatCheckFailure(report));
    } else {
      console.log(`${name}: ok (${report.deltas.length} metrics)`);
    }
  }
  process.exit(failed ? 1 : 0);
}

if (all || check) {
  console.error("Use --all and --check together: npm run probe -- --all --check");
  process.exit(1);
}

const name = positional[0];
if (!name) usage();

const result = runProbe(name);

if (writeBaseline) {
  const tols = BASELINE_TOLERANCES[name];
  if (!tols) {
    console.error(`No baseline tolerances registered for '${name}'`);
    process.exit(1);
  }
  const file = writeBaselineFile(result, tols);
  console.log(
    `Wrote docs/evidence/${name}.baseline.json (${Object.keys(file.metrics).length} metrics)`,
  );
  console.log(
    "State why this baseline moved in the commit body — unexplained moves are defects.",
  );
}

const report = compareToBaseline(result);
writeEvidenceMarkdown(result, report);
console.log(JSON.stringify({ scenario: result.scenario, records: result.records, report }, null, 2));
console.log(`Wrote docs/evidence/${result.scenario}.md`);

if (report.missingBaseline && !writeBaseline) {
  console.error(
    `Missing baseline for ${name}. Create with: npm run probe -- ${name} --write-baseline`,
  );
  process.exit(1);
}
